### PR TITLE
Use 'truncate table' to clear data before loading fixtures

### PR DESCRIPTION
**Pull request by aclemons**
Would you mind changing from using `DELETE FROM` to `TRUNCATE TABLE`? I have a probably somewhat questionable use case where this seems to be slightly faster. (Seeding some test data with fixation and then running some tests which generate heaps of data)

### CODE REVIEW

**Comment by willbryant** [comment]
Hmm.  Not really keen to do this as it is DDL rather than DML.  It requires different permissions and tends not to work with stuff like foreign key constraints, so it's not necessarily going to work for everyone; it's also not faster in all cases because recreating a table is slower if it was nearly empty before.

Having large amounts of test data is a strong antipattern - it implies that you are not writing meaningful fixtures - so I don't think it will be a good trade-off for many people.

I could probably be convinced to have an option for it, but maybe it would be better to just extract that line to its own method that you could monkeypatch locally when you're doing your special use case.

**Comment by aclemons** [comment]
I don't actually have that much test data, I was running some longer tests which end up with heaps of data in tables, but the initial data is small set of fixtures loaded by fixation. Reusing the same database for the second run is slow at times when fixation clears things, but this is something I can work around simply outside of fixation. Thanks.

**Comment by willbryant** [comment]
Hmm why doesn't it roll back at the end of the test?

**Comment by aclemons** [comment]
I am "misusing" fixation here, hence my questionable remark. I'm not running specs, but loading some fixture data with fixation and then running other things.

**Comment by willbryant** [comment]
Ah.  You could still use a transaction yourself and throw an ActiveRecord::Rollback at the end of the test?

**Comment by aclemons** [comment]
Sorry I am being unclear. This is loaded and then I am running multiple proceses with multiple threads against the database. The fixture data is mostly seed data. Fixation here was just a simple way to also clear the database before the test because this was something fixation already does. I can work around this easily though (drop db or reload schema etc)

**Comment by willbryant** [comment]
I see.  If that table is seeded, that is not the relevant bit of code, it's FixtureTable#statements that will actually do the DELETE.

But, you can't do a TRUNCATE in either place (and have things work properly) because it would end the transaction (on mysql).

So yeah, probably best that you run the TRUNCATE in a `before(:all)`, which is run before the test transaction is started and I _think_ is run before fixtures are inserted.  (If not, you might need to call `Fixation.apply_fixtures` a second time, or monkeypatch that.)

**Pull request closed without merging**
